Renaming
pangeo-forge/pangeo-forge pull request #122
Opened 2021-05-04 01:24 UTC by cisaacstern

Closes #75

A fourth (and hopefully final) attempt at this PR. In the second attempt, updating the package name in `.github/workflows/main.yaml` allowed tests to pass. In the third attept, wrapping a few lengthened import statements in `tests/` got pre-commit linting closer to passing. Trailing whitespace trimmed in this attempt should ideally get pre-commit to pass.

In addition to underscored name instances, I’ve also changed dashed name instances (i.e. ‘pangeo-forge’ became ‘pangeo-forge-recipes’). These dashed names are primarily in the README, but also appear in setup.py and perhaps a few other places.

Local testing indicates that, following these changes, the only failed test is test_fixture_local_files_by_variable (line 17 in tests/test_fixtures.py). I note, however, that this test is marked for replacement with a TODO comment, so perhaps this is not of great concern.

A final note on methodology, for the sake of record keeping: all of these name changes have been made with various versions of the command `find . -type f -print0 | xargs -0 sed -i '' -e 's/pangeo_forge/pangeo_forge_recipes/g'`, referenced from [this superuser thread](https://superuser.com/questions/428493/how-can-i-do-a-recursive-find-and-replace-from-the-command-line). Notably, I did not make all changes in one command from the top-level directory, as this appeared to break something in the git index; instead commands were executed in each relevant sub-directory one at a time. In the case of changes to individual files in the top-level directory, the `-name` flag was used, as demonstrated in the linked thread.

2021-05-04 12:17 UTC, rabernat requested changes
Excellent! Thanks @cisaacstern! Really impressed by your quick work here.

The only problem I see is probably due to my unclear instructions: we don't want to rename the whole `pangeo-forge` github organization (or any of the other sub-projects). We just want to rename _this repo_. In fact, if we rename everything, we will be back where we started, with no way to differentiate this python package from the broader project. 🙃 

Once you fix those instances, we will be good to go.

2021-05-04 12:17 UTC, rabernat commented on docs/bakeries.md
> +- <https://github.com/pangeo-forge-recipes/pangeo-forge-recipes-aws-bakery> -
So here it looks like you are also changing the name of the github org (`github.com/pangeo-forge`)  and another associated repo (`pangeo-forge-aws-bakery`). We _only_ want to rename this repo, not the org, nor the other project. So I would revert this.

2021-05-04 12:17 UTC, rabernat commented on docs/bakeries.md
> +- <https://github.com/pangeo-forge-recipes/pangeo-forge-recipes-azure-bakery> -
Same.

2021-05-04 12:17 UTC, rabernat commented on docs/conf.py
> +    "repository_url": "https://github.com/pangeo-forge-recipes/pangeo-forge-recipes",
Same. Don't rename the org, just the repo.

2021-05-04 12:17 UTC, rabernat commented on docs/conf.py
> +html_logo = "_static/pangeo-forge-recipes-logo-blue.png"
Unless you renamed the file, this will break the docs.

2021-05-04 12:17 UTC, rabernat commented on docs/recipe_box.md
> +1. [fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) the <https://github.com/pangeo-forge-recipes/staged-recipes> GitHub repository
Don't rename the org.

2021-05-04 12:17 UTC, rabernat commented on docs/tutorials/cmip6-recipe.ipynb
> +    "- If you find a CMIP6 dataset for which this recipe does not work, Please report it at [issue#105](https://github.com/pangeo-forge-recipes/pangeo-forge-recipes/issues/105) so we can refine the r
Don't rename the org.

2021-05-04 12:17 UTC, rabernat commented on setup.py
> +    url="https://github.com/pangeo-forge-recipes/pangeo-forge-recipes",
Don't rename the org.

2021-05-04 19:00 UTC, rabernat commented
FYI, it looks like we had a hung test, as happens from time to time. I restarted them.

2021-05-04 19:14 UTC, cisaacstern commented
@rabernat, the accidental org-renaming was the result of changing all `'pangeo-forge'` strings to `'pangeo-forge-recipes'`. While reversing this blanket change was a first step, I subsequently realized that there are certain edge cases where we do want to make this change: e.g., in the topline header of the README and, more frequently, in various places that link to (what will now be) https://github.com/pangeo-forge/pangeo-forge-recipes.

Beyond these obvious cases, there were a handful of edge cases where I was not entirely certain. I'll list the choices I made here, and you can decide if any of them should be corrected before merging:

1. In `/pangeo_forge_recipes/utils.py` the function `lock_for_conflicts` defined on line 87 uses the default kwarg `base-name="pangeo-forge"`. I left this as-is, in part because I wasn't clear on the purpose of this kwarg, and in part because it's marked for change with an in-line TODO comment.
2. In `Dockerfile` the final two lines now use `pangeo-forge-recipes`, which I believe is correct because the repo name itself will be changed to that, once this PR is merged.
3. In all three `.yml` files within the `/ci` directory, I've renamed the specified environments to `"pangeo-forge-recipes"`
4. In `setup.py`, the `name=` and `entry_points=` kwargs now use `pangeo-forge-recipes`, which was sort of just a best guess.
5. In `.github/workflows/main.yaml`, this PR now has `activate-environment: pangeo-forge-recipes`, which I believe makes it consistent with the changed env names in the `/ci` directory. In the same file, `- name: install pangeo-forge-recipes` was another best guess.
6. The string `"pangeo-forge"` pops up in a few of the tutorial notebooks as part of RuntimeWarnings. These are presumably part of notebook outputs, so I've left them unchanged.
7. The string `"pangeo-forge3.8"` appears twice as part of metadata in `/docs/tutorials/cmip6-recipe.ipynb`. This is presumably a kernel and/or environment name, but since it's the only place where I encountered this specific string, and I wasn't sure of its precise role, it sort of threw me off and I just left it as-is.

On a meta level, after writing this list, I'm left wondering if in the future it would be better to provide file- and line-specific comments like this in-line in the PR diff. Let me know if that would be stylistically preferable and I can look into how to adjust for future PRs.

2021-05-05 13:06 UTC, rabernat commented
> 1. In `/pangeo_forge_recipes/utils.py` the function `lock_for_conflicts` defined on line 87 uses the default kwarg `base-name="pangeo-forge"`. I left this as-is, in part because I wasn't clear on the purpose of this kwarg, and in part because it's marked for change with an in-line TODO comment.

Correct, this name doesn't matter. The name here is used to synchronize overlapping writes among different processes within a dask cluster.

> 2\. In `Dockerfile` the final two lines now use `pangeo-forge-recipes`, which I believe is correct because the repo name itself will be changed to that, once this PR is merged.

These are actually not used any more and should be removed from the repo. I'll do that soon.

2021-05-05 13:06 UTC, merged